theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Rafi Ahammed Morshed]
logo: /images/hs.jpg
description: [Turning Data into insights]
